"""Fail-closed local Paper execution contracts for P5."""

from .contracts import (
    EXECUTION_POLICY_ID,
    ExecutionContractError,
    ExecutionDisposition,
    ExecutionReason,
    LocalPaperExecutionDecision,
    LocalPaperExecutionPolicy,
    RecoveryReadiness,
    RecoveryReason,
    RecoveryStatus,
    assess_local_paper_authorization,
)
from .journal import (
    ExecutionIntentJournal,
    ExecutionJournalError,
    IntentConflict,
    LocalPaperIntentRecord,
)
from .state import (
    LocalOrderError,
    LocalOrderEventType,
    LocalOrderReason,
    LocalOrderStatus,
    LocalOrderTransitionError,
    LocalPaperOrderEvent,
    LocalPaperOrderState,
    LocalPaperOrderStore,
    LocalPaperOrderTransition,
    apply_local_order_event,
    build_local_order_event,
)
from .fills import (
    LocalPaperFillCostAdapter,
    LocalPaperFillError,
    LocalPaperFillStep,
)
from .portfolio import (
    DuplicateLocalPaperFill,
    LocalPaperFillEvent,
    LocalPaperPortfolioApplication,
    LocalPaperPortfolioError,
    LocalPaperPortfolioProjection,
    LocalPaperPortfolioStore,
)
from .reconcile import (
    RECONCILIATION_SCHEMA_VERSION,
    ReconciliationCode,
    StartupReconciliationError,
    StartupReconciliationReport,
    reconcile_startup,
)
from .recovery import (
    RECOVERY_SNAPSHOT_SCHEMA_VERSION,
    RecoveryCode,
    RecoveryReport,
    RecoverySnapshot,
    RecoverySnapshotError,
    confirm_pending_snapshot,
    create_recovery_snapshot,
    load_recovery_snapshot,
    recover_startup,
)

from .scenarios import (
    SCENARIOS as EXECUTION_SCENARIOS,
    ExecutionScenarioError,
    ExecutionScenarioMatrixResult,
    ExecutionScenarioResult,
    execution_matrix_sha256,
    run_adversarial_execution_matrix,
    run_and_write_adversarial_execution_matrix,
    scenario_artifact_json as execution_scenario_artifact_json,
    write_adversarial_execution_matrix,
)

__all__ = [
    "EXECUTION_POLICY_ID",
    "ExecutionContractError",
    "ExecutionDisposition",
    "ExecutionReason",
    "LocalPaperExecutionDecision",
    "LocalPaperExecutionPolicy",
    "RecoveryReadiness",
    "RecoveryReason",
    "RecoveryStatus",
    "assess_local_paper_authorization",
    "ExecutionIntentJournal",
    "ExecutionJournalError",
    "IntentConflict",
    "LocalPaperIntentRecord",
    "LocalOrderError",
    "LocalOrderEventType",
    "LocalOrderReason",
    "LocalOrderStatus",
    "LocalOrderTransitionError",
    "LocalPaperOrderEvent",
    "LocalPaperOrderState",
    "LocalPaperOrderStore",
    "LocalPaperOrderTransition",
    "apply_local_order_event",
    "build_local_order_event",
    "LocalPaperFillCostAdapter",
    "LocalPaperFillError",
    "LocalPaperFillStep",
    "DuplicateLocalPaperFill",
    "LocalPaperFillEvent",
    "LocalPaperPortfolioApplication",
    "LocalPaperPortfolioError",
    "LocalPaperPortfolioProjection",
    "LocalPaperPortfolioStore",
    "RECONCILIATION_SCHEMA_VERSION",
    "ReconciliationCode",
    "StartupReconciliationError",
    "StartupReconciliationReport",
    "reconcile_startup",
    "RECOVERY_SNAPSHOT_SCHEMA_VERSION",
    "RecoveryCode",
    "RecoveryReport",
    "RecoverySnapshot",
    "RecoverySnapshotError",
    "confirm_pending_snapshot",
    "create_recovery_snapshot",
    "load_recovery_snapshot",
    "recover_startup",
    "write_adversarial_execution_matrix",
    "execution_scenario_artifact_json",
    "run_and_write_adversarial_execution_matrix",
    "run_adversarial_execution_matrix",
    "execution_matrix_sha256",
    "ExecutionScenarioResult",
    "ExecutionScenarioMatrixResult",
    "ExecutionScenarioError",
    "EXECUTION_SCENARIOS",
]
