"""P10 Forward/Paper validation package."""

from .contracts import (
    P4_MAX_CONSECUTIVE_LOSSES,
    P4_MAX_DRAWDOWN_FRACTION,
    P4_MAX_SESSION_LOSS_FRACTION,
    P4_RISK_PER_TRADE_FRACTION,
    VALIDATION_CRITERIA,
    VALIDATION_POLICY_ID,
    VALIDATION_SCHEMA_VERSION,
    CandidateState,
    EconomicEvaluationState,
    ForwardDataState,
    RegistrationState,
    ThresholdState,
    ValidationCharter,
    ValidationContractError,
    ValidationCriterion,
    ValidationEvidenceState,
    ValidationPolicy,
    WindowState,
    validation_charter_from_record,
    validation_policy_from_record,
)

__all__ = [
    "P4_MAX_CONSECUTIVE_LOSSES",
    "P4_MAX_DRAWDOWN_FRACTION",
    "P4_MAX_SESSION_LOSS_FRACTION",
    "P4_RISK_PER_TRADE_FRACTION",
    "VALIDATION_CRITERIA",
    "VALIDATION_POLICY_ID",
    "VALIDATION_SCHEMA_VERSION",
    "CandidateState",
    "EconomicEvaluationState",
    "ForwardDataState",
    "RegistrationState",
    "ThresholdState",
    "ValidationCharter",
    "ValidationContractError",
    "ValidationCriterion",
    "ValidationEvidenceState",
    "ValidationPolicy",
    "WindowState",
    "validation_charter_from_record",
    "validation_policy_from_record",
]


from .registration import (
    CANDIDATE_ID,
    CANDIDATE_SOURCE_BLOBS,
    GATE_REGISTRY_ID,
    P10_001_POLICY_SHA256,
    REGISTRATION_ID,
    TREND_CONFIGURATION_SHA256,
    CandidateFreeze,
    CandidateFreezeState,
    CandidateGateRegistration,
    EconomicEvaluationState as RegisteredEconomicEvaluationState,
    EconomicGateRegistry,
    ForwardDataState as RegisteredForwardDataState,
    GateRegistrationState,
    RegistrationError,
    SourceBlobIdentity,
    ValidationWindowState,
    candidate_from_record,
    gate_registry_from_record,
    registration_from_record,
)

__all__ += [
    "CANDIDATE_ID",
    "CANDIDATE_SOURCE_BLOBS",
    "GATE_REGISTRY_ID",
    "P10_001_POLICY_SHA256",
    "REGISTRATION_ID",
    "TREND_CONFIGURATION_SHA256",
    "CandidateFreeze",
    "CandidateFreezeState",
    "CandidateGateRegistration",
    "RegisteredEconomicEvaluationState",
    "EconomicGateRegistry",
    "RegisteredForwardDataState",
    "GateRegistrationState",
    "RegistrationError",
    "SourceBlobIdentity",
    "ValidationWindowState",
    "candidate_from_record",
    "gate_registry_from_record",
    "registration_from_record",
]


from .window import (
    ACCEPTED_HISTORICAL_SOURCE_END_MS,
    ACCEPTED_SOURCE_ID,
    ACCEPTED_SOURCE_MANIFEST_GENERATED_AT_MS,
    ACCEPTED_SOURCE_MANIFEST_GIT_BLOB_SHA1,
    ACCEPTED_SOURCE_MANIFEST_PATH,
    FORWARD_WINDOW_START_MS,
    INTERVALS,
    MINIMUM_EVALUATION_NOT_BEFORE_MS,
    MINIMUM_VALIDATION_DAYS,
    P10_002_CHECKPOINT,
    P3_DEVELOPMENT_EVIDENCE_END_MS,
    SEALED_AT_MS,
    ForwardCollectionState,
    ForwardObservationIdentity,
    ForwardWindowSeal,
    WindowEvidenceState,
    WindowSealError,
    WindowSealState,
    EconomicEvaluationState as WindowEconomicEvaluationState,
    observation_identity_from_record,
    window_from_record,
)

__all__ += [
    "ACCEPTED_HISTORICAL_SOURCE_END_MS",
    "ACCEPTED_SOURCE_ID",
    "ACCEPTED_SOURCE_MANIFEST_GENERATED_AT_MS",
    "ACCEPTED_SOURCE_MANIFEST_GIT_BLOB_SHA1",
    "ACCEPTED_SOURCE_MANIFEST_PATH",
    "FORWARD_WINDOW_START_MS",
    "INTERVALS",
    "MINIMUM_EVALUATION_NOT_BEFORE_MS",
    "MINIMUM_VALIDATION_DAYS",
    "P10_002_CHECKPOINT",
    "P3_DEVELOPMENT_EVIDENCE_END_MS",
    "SEALED_AT_MS",
    "ForwardCollectionState",
    "ForwardObservationIdentity",
    "ForwardWindowSeal",
    "WindowEvidenceState",
    "WindowSealError",
    "WindowSealState",
    "WindowEconomicEvaluationState",
    "observation_identity_from_record",
    "window_from_record",
]
