"""P10 Forward/Paper validation package."""

from .contracts import (
    P4_MAX_CONSECUTIVE_LOSSES,
    P4_MAX_DRAWDOWN_FRACTION,
    P4_MAX_SESSION_LOSS_FRACTION,
    P4_RISK_PER_TRADE_FRACTION,
    VALIDATION_CRITERIA,
    VALIDATION_POLICY_ID,
    VALIDATION_SCHEMA_VERSION,
    CandidateState,
    EconomicEvaluationState,
    ForwardDataState,
    RegistrationState,
    ThresholdState,
    ValidationCharter,
    ValidationContractError,
    ValidationCriterion,
    ValidationEvidenceState,
    ValidationPolicy,
    WindowState,
    validation_charter_from_record,
    validation_policy_from_record,
)

__all__ = [
    "P4_MAX_CONSECUTIVE_LOSSES",
    "P4_MAX_DRAWDOWN_FRACTION",
    "P4_MAX_SESSION_LOSS_FRACTION",
    "P4_RISK_PER_TRADE_FRACTION",
    "VALIDATION_CRITERIA",
    "VALIDATION_POLICY_ID",
    "VALIDATION_SCHEMA_VERSION",
    "CandidateState",
    "EconomicEvaluationState",
    "ForwardDataState",
    "RegistrationState",
    "ThresholdState",
    "ValidationCharter",
    "ValidationContractError",
    "ValidationCriterion",
    "ValidationEvidenceState",
    "ValidationPolicy",
    "WindowState",
    "validation_charter_from_record",
    "validation_policy_from_record",
]
